

# This file was *autogenerated* from the file solver.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0p18 = RealNumber('0.18'); _sage_const_0 = Integer(0); _sage_const_10001 = Integer(10001); _sage_const_222 = Integer(222); _sage_const_5000 = Integer(5000); _sage_const_10 = Integer(10); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3)
from sage.all import *

def create_matrix(N, eq, X):
    ll = []
    

    

    a = eq.coefficients(sparse=False)

    d = eq.degree()
    #epsilon = min(1/d, 0.18)
    h = ceil((((_sage_const_1 /_sage_const_0p18 ))+_sage_const_1 )/d)
    #h = 3
    print(f'Degree: {d}')
    #print(f'Epsilon: {epsilon}')
    print(f'h: {h}')

    # bound if not given
    #X = 2^15

    G = []
    for i in range(d):
        for j in range(h):
            l = []

            for _ in range(i):
                l.append(_sage_const_0 )

            temp_eq = eq**j
            new_coeff = temp_eq.coefficients(sparse=False)
            precomputed = pow(N, h-_sage_const_1 -j)*pow(X,i)
            for exponent in range(len(new_coeff)):
                l.append(new_coeff[exponent]*precomputed*pow(X, exponent))
            G.append(l)
    
    max_length = _sage_const_0 
    for l in G:
        if len(l) > max_length:
            max_length = len(l)
    
    G.sort(key = len)

    for l in G:
        if len(l) < max_length:
            for v in range(max_length-len(l)):
                l.append(_sage_const_0 )

    for l in G:
        print(l)
    
    

    print(G)
    m = Matrix(G)
    print(m)

    

    M = m.LLL()
    print()
    print(M)
    print()


    #Q = M[0][0] + M[0][1]*x + M[0][2]*x^2 + M[0][3]*x^3 + M[0][4]*x^4 + M[0][5]*x^5 + M[0][6]*x^6 + M[0][7]*x^7 + M[0][8]*x^8
    for k in range(_sage_const_1 ):
        Q = _sage_const_0 
        for p in range(d*h):
            Q += (M[k][p]//(X**p))*x**p
        #Q = M[k][0] + M[k][1]*x + M[k][2]*x^2 + M[k][3]*x^3 + M[k][4]*x^4 + M[k][5]*x^5 + M[k][6]*x^6 + M[k][7]*x^7 + M[k][8]*x^8

        print(Q.roots(ring=ZZ))
    

#K = Zmod(10001)
#P.<x> = PolynomialRing(K, implementation='NTL')
R = PolynomialRing(ZZ, names=('x',)); (x,) = R._first_ngens(1)

# N = 4611686047418417197
# eq = 1942528644709637042 + 1234567890123456789*x + 987654321987654321*x^2 + x^3
# X = 2^14
N = _sage_const_10001 
eq = -_sage_const_222  + _sage_const_5000 *x + _sage_const_10 *x**_sage_const_2  + x**_sage_const_3 
X = _sage_const_10 


create_matrix(N, eq, X)

