

# This file was *autogenerated* from the file solutions.sage
from sage.all_cmdline import *   # import sage library

_sage_const_30 = Integer(30); _sage_const_7 = Integer(7); _sage_const_25 = Integer(25); _sage_const_11 = Integer(11); _sage_const_2 = Integer(2); _sage_const_16 = Integer(16); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_9 = Integer(9); _sage_const_28 = Integer(28); _sage_const_31 = Integer(31); _sage_const_0 = Integer(0)
couples = [ ([_sage_const_30 , _sage_const_7 , _sage_const_25 ], _sage_const_11 ), ([_sage_const_2 , _sage_const_16 , _sage_const_16 ], _sage_const_8 ), ([_sage_const_2 , _sage_const_4 , _sage_const_4 ], _sage_const_1 ), ([_sage_const_9 , _sage_const_25 , _sage_const_9 ], _sage_const_28 )]   # ( a_i, <a_i, s>)

A = matrix(GF(_sage_const_31 ), [couple[_sage_const_0 ] for couple in couples])
b = matrix(GF(_sage_const_31 ), [couple[_sage_const_1 ] for couple in couples]).transpose()
print((A.solve_right(b)).transpose())

